// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	common "github.com/tomvodi/limepipes-plugin-bww/internal/common"

	mock "github.com/stretchr/testify/mock"
)

// BwwFileByTuneSplitter is an autogenerated mock type for the BwwFileByTuneSplitter type
type BwwFileByTuneSplitter struct {
	mock.Mock
}

type BwwFileByTuneSplitter_Expecter struct {
	mock *mock.Mock
}

func (_m *BwwFileByTuneSplitter) EXPECT() *BwwFileByTuneSplitter_Expecter {
	return &BwwFileByTuneSplitter_Expecter{mock: &_m.Mock}
}

// SplitFileData provides a mock function with given fields: data
func (_m *BwwFileByTuneSplitter) SplitFileData(data []byte) (*common.BwwFileTuneData, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for SplitFileData")
	}

	var r0 *common.BwwFileTuneData
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*common.BwwFileTuneData, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([]byte) *common.BwwFileTuneData); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.BwwFileTuneData)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BwwFileByTuneSplitter_SplitFileData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SplitFileData'
type BwwFileByTuneSplitter_SplitFileData_Call struct {
	*mock.Call
}

// SplitFileData is a helper method to define mock.On call
//   - data []byte
func (_e *BwwFileByTuneSplitter_Expecter) SplitFileData(data interface{}) *BwwFileByTuneSplitter_SplitFileData_Call {
	return &BwwFileByTuneSplitter_SplitFileData_Call{Call: _e.mock.On("SplitFileData", data)}
}

func (_c *BwwFileByTuneSplitter_SplitFileData_Call) Run(run func(data []byte)) *BwwFileByTuneSplitter_SplitFileData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *BwwFileByTuneSplitter_SplitFileData_Call) Return(_a0 *common.BwwFileTuneData, _a1 error) *BwwFileByTuneSplitter_SplitFileData_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BwwFileByTuneSplitter_SplitFileData_Call) RunAndReturn(run func([]byte) (*common.BwwFileTuneData, error)) *BwwFileByTuneSplitter_SplitFileData_Call {
	_c.Call.Return(run)
	return _c
}

// NewBwwFileByTuneSplitter creates a new instance of BwwFileByTuneSplitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBwwFileByTuneSplitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BwwFileByTuneSplitter {
	mock := &BwwFileByTuneSplitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
